# Generated by Django 5.0.6 on 2025-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_rename_notesfile_notes_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('mobilenumber', models.CharField(default='', max_length=15)),
                ('emailid', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
