# Generated by Django 5.0.6 on 2025-04-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notes',
        ),
        migrations.AddField(
            model_name='files',
            name='filetype',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
