# Generated by Django 5.0.6 on 2025-04-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_remove_notes_notes_files_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='filetype',
        ),
    ]
