# Generated by Django 5.0.6 on 2024-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChairDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairtype', models.CharField(default='', max_length=100)),
                ('cost', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DecorationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decorationtype', models.CharField(default='', max_length=100)),
                ('itemused', models.CharField(default='', max_length=100)),
                ('cost', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(default='', max_length=100)),
                ('itemused', models.CharField(default='', max_length=100)),
                ('rate', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionhallname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('managername', models.CharField(default='', max_length=100)),
                ('contactnumber', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('cost', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('mobilenumber', models.CharField(default='', max_length=15)),
                ('emailid', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
