# Generated by Django 5.0.6 on 2024-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDetails1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('mobilenumber', models.CharField(default='', max_length=15)),
                ('emailid', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
