# Generated by Django 5.0.6 on 2024-06-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_registerdetails1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairdetails',
            old_name='cost',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='decorationdetails',
            old_name='cost',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='fooddetails',
            old_name='rate',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='halldetails',
            old_name='cost',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='decorationdetails',
            name='itemused',
        ),
    ]
