# Generated by Django 5.0.6 on 2024-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_cost_chairdetails_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairdetails',
            name='scquantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chairdetails',
            name='stagechair',
            field=models.CharField(default='', max_length=100),
        ),
    ]
