# Generated by Django 5.0.6 on 2024-06-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_chairdetails_scquantity_chairdetails_stagechair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairdetails',
            name='scquantity',
        ),
        migrations.RemoveField(
            model_name='chairdetails',
            name='stagechair',
        ),
    ]
