# Generated by Django 5.0.6 on 2024-06-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_chairdetails_scquantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairdetails',
            old_name='chairtype',
            new_name='scquantity',
        ),
    ]
