# Generated by Django 5.0.6 on 2024-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_chairtype_chairdetails_scquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairdetails',
            name='chairtype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chairdetails',
            name='stagechair',
            field=models.CharField(default='', max_length=100),
        ),
    ]
