# Generated by Django 5.0.6 on 2024-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_chairdetails_chairtype_chairdetails_stagechair'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='food',
            field=models.CharField(default='', max_length=100),
        ),
    ]
