# Generated by Django 5.0.6 on 2024-06-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_fooddetails_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='fooddetails',
            name='itemused',
        ),
        migrations.RemoveField(
            model_name='halldetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='halldetails',
            name='plates',
            field=models.CharField(default='', max_length=100),
        ),
    ]
