# Generated by Django 5.0.6 on 2024-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_fooddetails_itemname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='food',
        ),
        migrations.RemoveField(
            model_name='fooddetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='foodtype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='plates',
            field=models.CharField(default='', max_length=100),
        ),
    ]
