# Generated by Django 5.0.6 on 2024-06-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_fooddetails_food_remove_fooddetails_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddetails',
            old_name='foodtype',
            new_name='food',
        ),
    ]
