# Generated by Django 5.0.6 on 2024-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_foodtype_fooddetails_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='food',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='foodtypes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
