# Generated by Django 5.0.6 on 2024-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_fooddetails_food_fooddetails_foodtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='foodtypes',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='food',
            field=models.CharField(default='', max_length=100),
        ),
    ]
