# Generated by Django 5.0.6 on 2024-06-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_fooddetails_foodtypes_fooddetails_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='halldetails',
            old_name='address',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='halldetails',
            name='functionhallname',
        ),
    ]
