# Generated by Django 5.0.6 on 2024-06-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_rename_address_halldetails_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halldetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='halldetails',
            name='plates',
        ),
    ]
