# Generated by Django 5.0.6 on 2024-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_halldetails_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorationdetails',
            name='decorationtype',
        ),
        migrations.RemoveField(
            model_name='decorationdetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='decorationdetails',
            name='celebrationspot',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='decorationdetails',
            name='eventtype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='decorationdetails',
            name='theme',
            field=models.CharField(default='', max_length=100),
        ),
    ]
