# Generated by Django 5.0.6 on 2024-06-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_decorationdetails_decorationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halldetails',
            name='managername',
        ),
    ]
