# Generated by Django 5.0.6 on 2024-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_halldetails_managername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halldetails',
            name='contactnumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registerdetails',
            name='mobilenumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
