# Generated by Django 5.0.6 on 2024-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_halldetails_contactnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('mobilenumber', models.CharField(default='', max_length=100)),
                ('stagechair', models.CharField(default='', max_length=100)),
                ('scquantity', models.CharField(default='', max_length=100)),
                ('chairtype', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
                ('food', models.CharField(default='', max_length=100)),
                ('plates', models.CharField(default='', max_length=100)),
                ('venue', models.CharField(default='', max_length=100)),
                ('theme', models.CharField(default='', max_length=100)),
                ('eventtype', models.CharField(default='', max_length=100)),
                ('celebrationspot', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
