# Generated by Django 5.0.6 on 2024-06-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_savedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedetails',
            name='mobilenumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
