# Generated by Django 5.0.6 on 2024-07-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_savedetails_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedetails',
            name='chairtype',
        ),
        migrations.RemoveField(
            model_name='savedetails',
            name='scquantity',
        ),
        migrations.RemoveField(
            model_name='savedetails',
            name='stagechair',
        ),
    ]
