# Generated by Django 5.0.6 on 2024-07-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_remove_savedetails_chairtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedetails',
            old_name='celebrationspot',
            new_name='date',
        ),
    ]
