# Generated by Django 5.0.6 on 2025-03-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('notesfile', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
