# Generated by Django 5.0.6 on 2025-03-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notesfile',
            new_name='notes',
        ),
    ]
