# Generated by Django 5.0.6 on 2025-03-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_details1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
            ],
        ),
    ]
