# Generated by Django 5.1.4 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notes',
        ),
    ]
